neo4j-coordinator
=================
:author: The Neo4j Team

名称
--
neo4j-coordinator - 为Neo4j的高可用性集群提供的协调员


[[neo4j-coordinator-manpage]]
语法
--

*neo4j-coordinator* <command>

[[neo4j-coordinator-manpage-description]]
描述
--
Neo4j Coordinator is a server which provides coordination for a Neo4j High Availability Data cluster.
A "coordination cluster" must be started and available before the "data cluster" can be started. 
This server is a member of the cluster.

[[neo4j-coordinator-manpage-commands]]
命令
--

*console*::
  Start the server as an application, running as a foreground proces. Stop the server using `CTRL-C`.

*start*::
  Start server as daemon, running as a background process.

*stop*::
  Stops a running daemonized server.

*restart*::
  Restarts a running server.

*status*::
  Current running state of the server

*install*::
  Installs the server as a platform-appropriate system service.

*remove*::
  Uninstalls the system service

[[neo4j-coordinator-manpage-files]]
涉及到的相关配置文件
----------

*conf/coord.cfg*::
  Coordination server configuration.

*conf/coord-wrapper.cfg*::
  Configuration for service wrapper.

*data/coordinator/myid*::
  Unique identifier for coordinator instance.
  

