[[python-embedded-installation]]
安装
==

注意： Neo4j数据库（来自<<editions, 社区版>>）本身就被包括在Neo4j嵌入模式发行版中。
The Neo4j database itself (from the <<editions,Community Edition>>) is included in the neo4j-embedded distribution.

== 安装到OSX/Linux ==


=== 先决条件 ===

特别注意：确保使用的整个堆栈要么是64位的，要么是32位（默认就是32位）。这都是为了正常使用JVM，Python和JPype。

首先，安装JPype：

. 从http://sourceforge.net/projects/jpype/files/JPype/下载JPype的最新版本。
. 解压下载压缩包。
. 打开控制台，并进入压缩包目录。
. 运行命令：`sudo python setup.py install`。

JPype在Debian的源里面也有：

[source, shell]
----
sudo apt-get install python-jpype
----

然后，确保 +JAVA_HOME+环境参数设置到了你的'jre' 和 'jdk'目录，保证JPype呢给你找到JVM。

注意: 在OSX上面安装是有问题的。看下面在Stack Overflow的讨论来获取更多的帮助：http://stackoverflow.com/questions/8525193/cannot-install-jpype-on-os-x-lion-to-use-with-neo4j 。


=== 安装 neo4j-embedded ===

你可以用你的Python包管理工具安装neo4j-embedded：

[source, shell]
----
sudo pip install neo4j-embedded
----

[source, shell]
----
sudo easy_install neo4j-embedded
----

或者手工安装：

. 从 http://sourceforge.net/projects/jpype/files/JPype/[32位], http://www.lfd.uci.edu/~gohlke/pythonlibs/[64位]下载JPype最新版本。
. 解压下载的压缩文件。
. 打开控制台并进入到解压目录。
. 运行命令： `sudo python setup.py install`


== 安装到 Windows ==

=== 先决条件 ===

警告： 确保使用的整个堆栈要么是64位的，要么是32位（默认就是32位）。这都是为了正常使用JVM，Python，JPype和所有额外的DLL。

首先，安装JPype：

[NOTE]
注意JPype只工作在Python 2.6 和 2.7。
也要注意你下载的地址由你使用的版本决定。

. 从 http://sourceforge.net/projects/jpype/files/JPype/[32位], http://www.lfd.uci.edu/~gohlke/pythonlibs/[64位]下载JPype最新版本。
. 运行安装程序。

然后，确保 +JAVA_HOME+环境参数设置到了你的'jre' 和 'jdk'目录。
要了解详细的环境参数设置情况，请参考：<<python-embedded-installation-windows-dlls>>。

注意：如果有JPype需要的DLL文件缺失，请参考： <<python-embedded-installation-windows-dlls>> 的介绍来修复它。

=== 安装 neo4j-embedded ===

. 从http://pypi.python.org/pypi/neo4j-embedded/下载最新版本。
. 运行安装程序。

[[python-embedded-installation-windows-dlls]]
=== 解决缺失DLL 文件的问题 ===

Windows的某些版本缺失了需要编程启动一个JVM的DLL文件。
你需要保证 +IEShims.dll+和某些调试用的DLL文件在Windows上面。

+IEShims.dll+ 一般是在 Internet Explorer 的安装包里面。
要让这个文件在你的系统路径下面，你需要增加 IE 的安装目录到你的 +PATH+。

. 右键点击 "我的电脑" 或者 "电脑"。
. 选择 "属性"。
. 点击 "高级" 或者 "高级系统设置"。
. 点击 "环境变量" 按钮。
. 找到path变量，并增加路径 'C:\Program Files\Internet Explorer'  到他的后面（如果你的IE在其他目录，请用其他目录代替）。

调试涉及到的DLL文件都在Microsoft Visual C++ Redistributable库里面。

- 32bit Windows: http://www.microsoft.com/download/en/details.aspx?displaylang=en&id=5555
- 64bit Windows: http://www.microsoft.com/download/en/details.aspx?displaylang=en&id=14632

如果你依然还有问题，你可以使用 http://www.dependencywalker.com/ 打开你的 +jvm.dll+ （在 'JAVA_HOME/bin/client/' 或者 'JAVA_HOME/bin/server/' 下面），然后他会告诉你是否缺失文件。


