[[cla]]
贡献者许可协议
=======

== 总结 ==

我们要求所有托管在Neo4j上面的源代码都必须通过 http://dist.neo4j.org/neo4j-cla.pdf[Neo4j Contributor License Agreement] (CLA)贡献出来。这个协议的目的是为了保护完整的代码库，反过来也保护代码库周围的社区：创始公司Neo Technology，Neo4j开发社区以及Neo4j用户。 贡献者协议类型跟很多开源软件和开源工程类似（实际上，他非常类似于广泛签署的 http://www.oracle.com/technetwork/community/oca-486395.html[Oracle Contributor Agreement]）。

如果你没有CLA协议的其他任何问题，请继续浏览下面的内容或者发送邮件到地址： admins@neofourjay.org 。如果你有一个法律问题，请咨询律师。

== 一般问题 ==

=== 我会失去我自己代码的权利吗？ ===

不会，http://dist.neo4j.org/neo4j-cla.pdf[Neo4j CLA]只要求你共享你的权利，而不是要你放弃你的权利。不像一些贡献协议，要求您转移到另一个组织的版权。CLA并不会带走你的知识产权。当你同意CLA协议时，您授予我们共同拥有版权以及你的贡献的一个专利授权。你保留所有权利，所有权和利益，你可以把它们用正你任何你希望的地方。除了撤销我们的权利，你还可以对你的代码做任何事情。

=== 你们会如何处理我贡献的东西？ ===

我们可以行使版权持有人的所有权利，以及拥有您在http://dist.neo4j.org/neo4j-cla.pdf[Neo4j CLA]中授权给我们的你拥有的权利。在CLA提供的联合版权的所有权中，在你的贡献上，你可行使和我们相同的权利。

=== 为此社区会提供什么福利？ ===

嗯，它可以让我们赞助Neo4j重点项目和为社区提供基础设施，以便缺博啊我们能引入这些到软件中，我们发送给我们的客户没有任何讨厌的惊喜。没有这个能力，我们作为一个小公司将很难发布我们所有的代码作为免费软件。

而且，CLA协议让阿功能我们保护社区成员（包括开发者和用户）在有需要时面对有敌意的知识产品诉讼。这是与其他自由软件管家维护项目（除了与自由软件基金会（FSF），没有共享的版权而是你完全签署的FSF）是一样的，比如 http://www.fsf.org[Free Software Foundation - FSF]。贡献者协议页包括一份"自由软件公约"或者说一个承诺：贡献的东西将保持作为免费软件。

直到最后，你仍然保留你的贡献的所有权利而我们非常有信息的说：我们能保护Neo4j社区以及Neo4j公司的客户。

=== 我们可以讨论一些CLA里面的条款吗？ ===

绝对可以的！请告诉我们你的反馈！But let's keep the legalese off the mailing lists。请把你的反馈信息直接发送邮件到cla@neotechnology.com，我们会尽快回复你的。

=== 我仍然不喜欢CLA协议。 ===

好的，当然你也可以把你的代码或者稳定托管到其他任何地方。请不要！ 我们只是在这讨论下我们提供的基础设施的规则而已。

==  如何签署CLA协议 ==

当你已经阅读完了CLA，请你发送一份邮件到：cla@neotechnology.com。包括下面一些信息：

* 你的完整姓名（包括中文名和英文名）。
* 你的常用电子邮件。
* http://dist.neo4j.org/neo4j-cla.pdf[Neo4j CLA]协议的一份拷贝作为附件发送。
* 你同意这个协议的表述。

举个例子：

----
Hi. My name is John Doe (john@doe.com).
I agree to the terms in the attached Neo4j Contributor License Agreement.
----

