[[usage-data-collector]]
使用数据收集器
=======

Neo4j使用数据收集器是一个收集使用数据的子系统，报告提交到在ud.neo4j.org的UDC-server。
它很容易关闭，而不再收集机密数据。关于发送数据的详细细节，请参考下面的章节。

Neo4j团队使用这些信息作为一个来自Neo4j社区的自动，高效反馈的一种形式。
我们想通过匹配使用统计和下载统计来验证我们做了正确的事情。
在每一次发行后，我们能看到服务器软件释放有更大的保留空间。

收集的数据清楚地统计在这。
如果这个系统将来的任何版本收集额外的数据，我们将清楚地宣布哪些变更。

Neo4j团队非常尊重你的隐私。我们不会公布您的任何隐私信息。


== 技术信息 ==

为了收集关于Neo4j使用的更好的统计数据，UDC收集下面这些信息：

* 内核版本：构建编号。
* 存储编号： 在一个数据库在被创建是随机生成的一个全局唯一标识符。
* PING的次数：UDC内部维持一个PING的计数器，在内核重启后重置。
* 来源：有 "neo4j" or "maven"。如果你是从网站下载的Neo4j，那么就是 "neo4j" ; 如果你是使用Maven获取的Neo4j,那么就是 "maven" 。
* Java版本：使用的Java的版本号
* MAC地址
* 注册编号：注册服务器实例的编号
* 关于执行环境上下文的一些标签（比如：test, language, web-container, app-container, spring, ejb）。
* Neo4j发行版本(community, advanced, enterprise)。
* 当前集群名称的一个hash（如果存在集群名称的话）。
* Linux的发行信息（rpm, dpkg, unknown）。
* 追踪REST客户端驱动的User-Agent头信息。

在启动后，UDC在发送第一个PING之前等待10分钟。这基于两方面原因：首先我们不希望因为UDC降低了启动速度; 其次，我们希望保持一个PING来进行最小程序的自动测试。到UDC服务器的PING是通过一个HTTP GET方式完成的。


== 如何关闭UDC功能 ==

我们试图让大家更容易关闭UDC。实际上，UDC的代码集成在内核里面而不是一个完全独立的模块。

你可以通过下面两种方式关闭UDC：

. 最容易的方式是移除 neo4j-udc-*.jar 文件，这样内核就加载不了UDC,从而不会自动发送PING请求。

. 如果你使用Maven,并且希望UDC不再安装到你的系统，你可以如下配置：
+
[source,xml]
--------------------
 <dependency>
   <groupId>org.neo4j</groupId>
   <artifactId>neo4j</artifactId>
   <version>${neo4j-version}</version>
   <exclusions>
     <exclusion>
       <groupId>org.neo4j</groupId>
       <artifactId>neo4j-udc</artifactId>
     </exclusion>
   </exclusions>
 </dependency>
--------------------
+
_参数 $\{neo4j-version} 是Neo4j的版本。_

. 最后，如果你正在使用Neo4j的一个封装版本，而又不想改变任何jar文件，你可以通过一个系统配置参数： +-Dneo4j.ext.udc.disable=true+ 来关闭UDC。

